feat: use JH_CRYPTOMEDIC_UPLOAD_HOST

diff --git a/bin/cr-deploy-patch b/bin/cr-deploy-patch
--- a/bin/cr-deploy-patch
+++ b/bin/cr-deploy-patch
@@ -21,13 +21,18 @@ truncate --size=0 "$LOG"
 # We use this file in lftp_mkdir
 truncate --size=0 "$REMOTE_LISTING"
 
-export CRYPTOMEDIC_UPLOAD_HOST="ftp.cluster003.ovh.net"
+export CRYPTOMEDIC_UPLOAD_HOST="${CRYPTOMEDIC_UPLOAD_HOST:-$JH_CRYPTOMEDIC_UPLOAD_HOST}"
 export CRYPTOMEDIC_HTTP_HOST="www.cryptomedic.org"
 export CRYPTOMEDIC_HTTP_PORT=80
 
 export CRYPTOMEDIC_UPLOAD_USER="${CRYPTOMEDIC_UPLOAD_USER:-$JH_CRYPTOMEDIC_UPLOAD_USER}"
 export CRYPTOMEDIC_UPLOAD_PASSWORD="${CRYPTOMEDIC_UPLOAD_PASSWORD:-$JH_CRYPTOMEDIC_UPLOAD_PASSWORD}"
 export CRYPTOMEDIC_DB_UPGRADE="${CRYPTOMEDIC_DB_UPGRADE:-$JH_CRYPTOMEDIC_DB_UPGRADE}"
+
+if [ -z "$CRYPTOMEDIC_UPLOAD_HOST" ]; then
+	echo "Missing CRYPTOMEDIC_UPLOAD_HOST" >&2
+	exit 255
+fi
 
 if [ -z "$CRYPTOMEDIC_UPLOAD_USER" ]; then
 	echo "Missing CRYPTOMEDIC_UPLOAD_USER" >&2
