refactor: use new variable names

diff --git a/bin/cr-deploy-patch b/bin/cr-deploy-patch
--- a/bin/cr-deploy-patch
+++ b/bin/cr-deploy-patch
@@ -21,26 +21,26 @@ truncate --size=0 "$LOG"
 # We use this file in lftp_mkdir
 truncate --size=0 "$REMOTE_LISTING"
 
-export CRYPTOMEDIC_UPLOAD_HOST="${CRYPTOMEDIC_UPLOAD_HOST:-$JH_CRYPTOMEDIC_DEPLOY_HOST}"
+export CRYPTOMEDIC_DEPLOY_HOST="${CRYPTOMEDIC_DEPLOY_HOST:-$JH_CRYPTOMEDIC_DEPLOY_HOST}"
 export CRYPTOMEDIC_HTTP_HOST="www.cryptomedic.org"
 export CRYPTOMEDIC_HTTP_PORT=80
 
-export CRYPTOMEDIC_UPLOAD_USER="${CRYPTOMEDIC_UPLOAD_USER:-$JH_CRYPTOMEDIC_DEPLOY_USER}"
-export CRYPTOMEDIC_UPLOAD_PASSWORD="${CRYPTOMEDIC_UPLOAD_PASSWORD:-$JH_CRYPTOMEDIC_DEPLOY_PASSWORD}"
+export CRYPTOMEDIC_DEPLOY_USER="${CRYPTOMEDIC_DEPLOY_USER:-$JH_CRYPTOMEDIC_DEPLOY_USER}"
+export CRYPTOMEDIC_DEPLOY_PASSWORD="${CRYPTOMEDIC_DEPLOY_PASSWORD:-$JH_CRYPTOMEDIC_DEPLOY_PASSWORD}"
 export CRYPTOMEDIC_DB_UPGRADE="${CRYPTOMEDIC_DB_UPGRADE:-$JH_CRYPTOMEDIC_WEB_TOKEN}"
 
-if [ -z "$CRYPTOMEDIC_UPLOAD_HOST" ]; then
-	echo "Missing CRYPTOMEDIC_UPLOAD_HOST" >&2
+if [ -z "$CRYPTOMEDIC_DEPLOY_HOST" ]; then
+	echo "Missing CRYPTOMEDIC_DEPLOY_HOST" >&2
 	exit 255
 fi
 
-if [ -z "$CRYPTOMEDIC_UPLOAD_USER" ]; then
-	echo "Missing CRYPTOMEDIC_UPLOAD_USER" >&2
+if [ -z "$CRYPTOMEDIC_DEPLOY_USER" ]; then
+	echo "Missing CRYPTOMEDIC_DEPLOY_USER" >&2
 	exit 255
 fi
 
-if [ -z "$CRYPTOMEDIC_UPLOAD_PASSWORD" ]; then
-	echo "Missing CRYPTOMEDIC_UPLOAD_PASSWORD" >&2
+if [ -z "$CRYPTOMEDIC_DEPLOY_PASSWORD" ]; then
+	echo "Missing CRYPTOMEDIC_DEPLOY_PASSWORD" >&2
 	exit 255
 fi
 
@@ -55,11 +55,11 @@ fi
 exec 3>&1
 
 ftp_exec_raw() {
-	# tee -a "$LOG" | ftp "ftp://${CRYPTOMEDIC_UPLOAD_USER}:${CRYPTOMEDIC_UPLOAD_PASSWORD}@${CRYPTOMEDIC_UPLOAD_HOST}" 2>&1 | tee -a "$LOG"
+	# tee -a "$LOG" | ftp "ftp://${CRYPTOMEDIC_DEPLOY_USER}:${CRYPTOMEDIC_DEPLOY_PASSWORD}@${CRYPTOMEDIC_DEPLOY_HOST}" 2>&1 | tee -a "$LOG"
 
-	SSHPASS="${CRYPTOMEDIC_UPLOAD_PASSWORD}" sshpass -e \
+	SSHPASS="${CRYPTOMEDIC_DEPLOY_PASSWORD}" sshpass -e \
 		sftp -o "UserKnownHostsFile=$SWD/../conf/ovh.key" \
-		"${CRYPTOMEDIC_UPLOAD_USER}@${CRYPTOMEDIC_UPLOAD_HOST}" \
+		"${CRYPTOMEDIC_DEPLOY_USER}@${CRYPTOMEDIC_DEPLOY_HOST}" \
 		2>&1 | tee -a "$LOG"
 }
 
@@ -107,9 +107,9 @@ ftp_rm() {
 }
 
 header_begin "Dump infos"
-echo "CRYPTOMEDIC_UPLOAD_HOST: '${CRYPTOMEDIC_UPLOAD_HOST}'"
-echo "CRYPTOMEDIC_UPLOAD_USER: ${#CRYPTOMEDIC_UPLOAD_USER} characters"
-echo "CRYPTOMEDIC_UPLOAD_PASSWORD: ${#CRYPTOMEDIC_UPLOAD_PASSWORD} characters"
+echo "CRYPTOMEDIC_DEPLOY_HOST: '${CRYPTOMEDIC_DEPLOY_HOST}'"
+echo "CRYPTOMEDIC_DEPLOY_USER: ${#CRYPTOMEDIC_DEPLOY_USER} characters"
+echo "CRYPTOMEDIC_DEPLOY_PASSWORD: ${#CRYPTOMEDIC_DEPLOY_PASSWORD} characters"
 header_end
 
 header_begin "Testing connectivity"
