refactor: use CRYPTOMEDIC_WEB_TOKEN

diff --git a/bin/cr-deploy-patch b/bin/cr-deploy-patch
--- a/bin/cr-deploy-patch
+++ b/bin/cr-deploy-patch
@@ -27,7 +27,7 @@ export CRYPTOMEDIC_HTTP_PORT=80
 
 export CRYPTOMEDIC_DEPLOY_USER="${CRYPTOMEDIC_DEPLOY_USER:-$JH_CRYPTOMEDIC_DEPLOY_USER}"
 export CRYPTOMEDIC_DEPLOY_PASSWORD="${CRYPTOMEDIC_DEPLOY_PASSWORD:-$JH_CRYPTOMEDIC_DEPLOY_PASSWORD}"
-export CRYPTOMEDIC_DB_UPGRADE="${CRYPTOMEDIC_DB_UPGRADE:-$JH_CRYPTOMEDIC_WEB_TOKEN}"
+export CRYPTOMEDIC_WEB_TOKEN="${CRYPTOMEDIC_WEB_TOKEN:-$JH_CRYPTOMEDIC_WEB_TOKEN}"
 
 if [ -z "$CRYPTOMEDIC_DEPLOY_HOST" ]; then
 	echo "Missing CRYPTOMEDIC_DEPLOY_HOST" >&2
@@ -44,8 +44,8 @@ if [ -z "$CRYPTOMEDIC_DEPLOY_PASSWORD" ]; then
 	exit 255
 fi
 
-if [ -z "$CRYPTOMEDIC_DB_UPGRADE" ]; then
-	echo "Missing CRYPTOMEDIC_DB_UPGRADE" >&2
+if [ -z "$CRYPTOMEDIC_WEB_TOKEN" ]; then
+	echo "Missing CRYPTOMEDIC_WEB_TOKEN" >&2
 	exit 255
 fi
 
